<?php

return [
    'model' => \Callmeaf\Variation\Models\Variation::class,
    'model_resource' => \Callmeaf\Variation\Http\Resources\V1\Api\VariationResource::class,
    'model_resource_collection' => \Callmeaf\Variation\Http\Resources\V1\Api\VariationCollection::class,
    'service' => \Callmeaf\Variation\Services\V1\VariationService::class,
    'default_values' => [
        'status' => \Callmeaf\Variation\Enums\VariationStatus::PRODUCT,
        'nature' => \Callmeaf\Variation\Enums\VariationNature::DEBTOR,
    ],
    'events' => [
        \Callmeaf\Variation\Events\VariationIndexed::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationStored::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationShowed::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationUpdated::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationStatusUpdated::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationDestroyed::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationRestored::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationTrashed::class => [
            // listeners
        ],
        \Callmeaf\Variation\Events\VariationImageUpdated::class => [
            // listeners
        ],
    ],
    'validations' => [
        'variation' => \Callmeaf\Variation\Utilities\V1\Variation\Api\VariationFormRequestValidator::class,
    ],
    'resources' => [
        'index' => [
            'relations' => [
                'product',
                'media',
                'type',
            ],
            'columns' => [
                'id',
                'variation_type_id',
                'status',
                'sku',
                'title',
                'price',
                'discount_price',
                'created_at',
                'updated_at',
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'id',
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
                'image',
                '!image' => [
                    'id',
                    'url',
                    'name',
                    'file_name',
                    'collection_name',
                    'mime_type',
                    'disk',
                    'size',
                ],
                'type',
                '!type' => [
                    'id',
                    'status',
                    'status_text',
                    'cat',
                    'cat_text',
                    'title',
                    'content',
                    'created_at_text',
                    'updated_at_text',
                ],
            ],
        ],
        'store' => [
            'relations' => [
                'product'
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
                'image',
                '!image' => [
                    'id',
                    'url',
                    'name',
                    'file_name',
                    'collection_name',
                    'mime_type',
                    'disk',
                    'size',
                ],
            ],
        ],
        'show' => [
            'relations' => [
                'product',
                'type',
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'content',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
                'image',
                '!image' => [
                    'id',
                    'url',
                    'name',
                    'file_name',
                    'collection_name',
                    'mime_type',
                    'disk',
                    'size',
                ],
                'type',
                '!type' => [
                    'id',
                    'cat',
                    'title',
                ],
            ],
        ],
        'update' => [
            'relations' => [
                'product',
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
                'image',
                '!image' => [
                    'id',
                    'url',
                    'name',
                    'file_name',
                    'collection_name',
                    'mime_type',
                    'disk',
                    'size',
                ],
            ],
        ],
        'status_update' => [
            'relations' => [
                'product',
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
            ],
        ],
        'destroy' => [
            'attributes' => [
                'id',
            ],
        ],
        'image_update' => [
            'relations' => [
                'product',
            ],
            'attributes' => [
                'id',
                'status',
                'status_text',
                'sku',
                'title',
                'price',
                'price_text',
                'discount_price',
                'discount_price_text',
                'created_at_text',
                'updated_at_text',
                'product',
                '!product' => [
                    'type',
                    'status',
                    'title',
                    'slug',
                    'product_id',
                    'type',
                    'type_text',
                    'status',
                    'status_text',
                    'title',
                    'slug',
                    'created_at_text',
                    'updated_at_text',
                    'published_at_text',
                    'expired_at_text',
                ],
                'image',
                '!image' => [
                    'id',
                    'url',
                    'name',
                    'file_name',
                    'collection_name',
                    'mime_type',
                    'disk',
                    'size',
                ],
            ],
        ],
    ],
    'controllers' => [
        'variations' => \Callmeaf\Variation\Http\Controllers\V1\Api\VariationController::class,
    ],
    'form_request_authorizers' => [
        'variation' => \Callmeaf\Variation\Utilities\V1\Variation\Api\VariationFormRequestAuthorizer::class,
    ],
    'middlewares' => [
        'variation' => \Callmeaf\Variation\Utilities\V1\Variation\Api\VariationControllerMiddleware::class,
    ],
    'searcher' => \Callmeaf\Variation\Utilities\V1\Variation\Api\VariationSearcher::class,
    'prefix_sku' => 'callmeaf-',
    'sku_length' => 6,
];
